language: python
python:
  - '2.7'
install: pip install -r requirements.txt
before_script:
  - psql -c 'create database testing_db;' -U postgres
script: bash travis.bash
script: nosetests tests.py
branches:
  except:
    - travis-ci
env:
  global:
    secure: "DSZxg9+1wRtSz9BWt+rDM6WnfW6nUlqbQEoVvsZT8kcut6tZwRKY7fHIGH9A/bqUVinADQ7791QtUcMch6w87ZWix7u4FuPLEpL6QX4C8nvhWrLdcEA4kPQHIN3ok8JFLgKr+2hvd7TWyZe7YacWzfBx/taw6tR+SdE7ey0u2sw="